Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

    config.vm.define "acs" do |acs|
      acs.vm.box = "centos/7"
      acs.vm.hostname = "acs"
      acs.vm.network "private_network", ip: "192.168.10.10"
    end

    config.vm.define "app1i" do |web|
      web.vm.box = "centos/7"
      web.vm.hostname = "app1i"
      web.vm.network "private_network", ip: "192.168.10.21"
      web.vm.network "forwarded_port", guest: 80, host: 8080
    end

    config.vm.define "app2i" do |web|
      web.vm.box = "centos/7"
      web.vm.hostname = "app2i"
      web.vm.network "private_network", ip: "192.168.10.22"
      web.vm.network "forwarded_port", guest: 80, host: 8081
    end

    config.vm.define "app3i" do |web|
      web.vm.box = "centos/7"
      web.vm.hostname = "app3i"
      web.vm.network "private_network", ip: "192.168.10.23"
      web.vm.network "forwarded_port", guest: 80, host: 8082
    end

    config.vm.define "db1i" do |db|
      db.vm.box = "centos/7"
      db.vm.hostname = "db1i"
      db.vm.network "private_network", ip: "192.168.10.31"
    end

    config.vm.define "db2i" do |db|
      db.vm.box = "centos/7"
      db.vm.hostname = "db2i"
      db.vm.network "private_network", ip: "192.168.10.32"
    end

    config.vm.define "db3i" do |db|
      db.vm.box = "centos/7"
      db.vm.hostname = "db3i"
      db.vm.network "private_network", ip: "192.168.10.33"
    end

    config.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/home/vagrant/.ssh/id_rsa"


  config.vm.provision "shell", inline: <<-SHELL
#! /bin/bash

  # Install ansible
  echo "--- install ansible"
  sudo yum -y install epel-release
  sudo yum -y install ansible

  # Install git
  sudo yum -y install git

  # Install ansible-lint
  curl -O https://bootstrap.pypa.io/get-pip.py
  python get-pip.py --user
  pip install ansible-lint

  # Change private key permissions
  sudo chmod 600 /home/vagrant/.ssh/id_rsa

  SHELL
end
