Vagrant.configure("2") do |config|
  config.ssh.insert_key = false

    config.vm.define "acs" do |acs|
      acs.vm.box = "centos/7"
      acs.vm.hostname = "acs"
      acs.vm.network "private_network", ip: "192.168.10.10"
    end

    config.vm.provision "file", source: "~/.vagrant.d/insecure_private_key", destination: "/home/vagrant/.ssh/id_rsa"
    config.vm.synced_folder "..", "/vagrant",type:"virtualbox",mount_options: ['dmode=777','fmode=644']

  config.vm.provision "shell", inline: <<-SHELL
#! /bin/bash

  # Update Kernel for Guest Additions
  sudo yum update kernel -y
  sudo yum install kernel-devel gcc -y

  # Install ansible
  sudo yum -y install epel-release
  sudo yum -y install ansible

  # Install git
  sudo yum -y install git

  # Install ansible-lint
  curl -O https://bootstrap.pypa.io/get-pip.py
  python get-pip.py --user
  pip install ansible-lint

  # Change private key permissions
  sudo chmod 600 /home/vagrant/.ssh/id_rsa

  # sudo mkdir /mnt/cdrom
  # sudo mount /dev/cdrom /mnt/cdrom

  # export KERN_DIR=/usr/src/kernels/3.10.0-1160.6.1.el7.x86_64/
  # sudo /mnt/cdrom/VBoxLinuxAdditions.run


  SHELL
end
