---
# SELinuxのモード変更
- name: configure / SELinux permissived
  selinux:
    policy: targeted
    state: permissive
  when: ansible_selinux.config_mode == 'enforcing'

# IPv6インターフェイスの無効化
- name: configure / Disable ipv6 interface
  sysctl:
    state: present
    name: "{{ item }}"
    value: 1
    sysctl_set: yes
    reload: yes
  with_items:
    - net.ipv6.conf.all.disable_ipv6
    - net.ipv6.conf.default.disable_ipv6

# YUMパッケージのアップデート
- name: configure / Update yum packages
  yum:
    name: '*'
    state: latest
    update_cache: yes

# EPELリポジトリの設定
- name: configure / Import EPEL Repository
  yum:
    name: epel-release
    state: latest
    update_cache: yes
