# (1)ホスト名の設定
- name: Set hostname
  hostname:
    name: "{{ inventory_hostname }}"

- name: Set resolver setting
  ini_file:
    dest: /etc/NetworkManager/NetworkManager.conf
    section: main
    option: dns
    value: none

# - name: Deploy nsswitch.conf
#   copy:
#     src: nsswitch.conf
#     dest: /etc/nsswitch.conf
#     owner: root
#     group: root
#     mode: 0644

# - name: Deploy resolv.conf
#   copy:
#     src: resolv.conf
#     dest: /etc/resolv.conf
#     owner: root
#     group: root
#     mode: 0644

# - name: Deploy hosts file
#   template:
#     src: hosts.j2
#     dest: /etc/hosts
#     owner: root
#     group: root
#     mode: 0644
